# Use root/example as user/password credentials
version: '3.1'

volumes:
  db_data:

services:

  mongo:
    container_name: mongodb_${MONGO_VERSION:-latest}
    image: mongo:${MONGO_VERSION:-latest}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-example}
    volumes:
      - db_data:/data/db
    ports:
      - "${MONGO_PORT:-27017}:27017"

  mongo-express:
    image: mongo-express:${MONGO_EXPRESS_VERSION:-latest}
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT:-8081}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD:-example}